# Generated by Django 5.1 on 2025-02-16 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='age',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='animal',
            name='gender',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='animal',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='animal',
            name='species',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
