# Generated by Django 5.1 on 2025-02-23 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_animal_age_animal_gender_animal_is_available_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='animal_type',
            field=models.CharField(blank=True, choices=[('Beef', 'Beef'), ('Dairy', 'Dairy')], max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='animal',
            name='medical_certificate',
            field=models.FileField(blank=True, null=True, upload_to='medical_certificates/'),
        ),
        migrations.AddField(
            model_name='animal',
            name='weight',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
