# Generated by Django 5.1 on 2025-02-23 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_animal_animal_type_animal_medical_certificate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='status',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
